
# Common config
spring.output.ansi.enabled: ALWAYS

server:
  context-path: /destrol
  port: 8088

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/github/destrol/mapper/*.xml

# Activated by default
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev

# Datasource config
druid:
  driver-class: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/avatar
  username: freshman
  password: avatar#?2017
  initial-size: 0
  max-active: 20
  min-idle: 1
  max-wait: 60000

---
spring:
  profiles: prod

# Datasource config
druid:
  driver-class: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/avatar
  username: freshman
  password: avatar#?2017
  initial-size: 0
  max-active: 20
  min-idle: 1
  max-wait: 60000
